---
#
# Ansible managed
#
repository:
  description: Install and configure roundcubemail on your system.
  homepage: https://robertdebock.nl/
  topics: roundcubemail, ansible, molecule, tox, playbook, hacktoberfest
