---
sudo: required
language: python
services: docker

env:
  - version=">=2.7,<2.8" distro="alpine-latest"
  - version="" distro="alpine-latest"
  - version="devel" distro="alpine-latest"
  - version=">=2.7,<2.8" distro="alpine-edge"
  - version="" distro="alpine-edge"
  - version="devel" distro="alpine-edge"
  - version=">=2.7,<2.8" distro="archlinux"
  - version="" distro="archlinux"
  - version="devel" distro="archlinux"
  - version=">=2.7,<2.8" distro="centos-6" expectation="fail"
  - version="" distro="centos-6" expectation="fail"
  - version="devel" distro="centos-6" expectation="fail"
  - version=">=2.7,<2.8" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"
  - version=">=2.7,<2.8" distro="debian-stable"
  - version="" distro="debian-stable"
  - version="devel" distro="debian-stable"
  - version=">=2.7,<2.8" distro="debian-unstable"
  - version="" distro="debian-unstable"
  - version="devel" distro="debian-unstable"
  - version=">=2.7,<2.8" distro="fedora-latest"
  - version="" distro="fedora-latest"
  - version="devel" distro="fedora-latest"
  - version=">=2.7,<2.8" distro="fedora-rawhide"
  - version="" distro="fedora-rawhide"
  - version="devel" distro="fedora-rawhide"
  - version=">=2.7,<2.8" distro="opensuse-leap"
  - version="" distro="opensuse-leap"
  - version="devel" distro="opensuse-leap"
  - version=">=2.7,<2.8" distro="ubuntu-rolling"
  - version="" distro="ubuntu-rolling"
  - version="devel" distro="ubuntu-rolling"
  - version=">=2.7,<2.8" distro="ubuntu-latest"
  - version="" distro="ubuntu-latest"
  - version="devel" distro="ubuntu-latest"
  - version=">=2.7,<2.8" distro="ubuntu-devel"
  - version="" distro="ubuntu-devel"
  - version="devel" distro="ubuntu-devel"

matrix:
  allow_failures:
    - env: version=">=2.7,<2.8" distro="alpine-edge"
    - env: version="" distro="alpine-edge"
    - env: version="devel" distro="alpine-edge"
    - env: version="devel" distro="alpine-latest"
    - env: version="devel" distro="archlinux"
    - env: version="devel" distro="centos-6" expectation="fail"
    - env: version="devel" distro="centos-latest"
    - env: version="devel" distro="debian-stable"
    - env: version=">=2.7,<2.8" distro="debian-unstable"
    - env: version="" distro="debian-unstable"
    - env: version="devel" distro="debian-unstable"
    - env: version="devel" distro="fedora-latest"
    - env: version=">=2.7,<2.8" distro="fedora-rawhide"
    - env: version="" distro="fedora-rawhide"
    - env: version="devel" distro="fedora-rawhide"
    - env: version="devel" distro="opensuse-leap"
    - env: version="devel" distro="ubuntu-rolling"
    - env: version=">=2.7,<2.8" distro="ubuntu-devel"
    - env: version="" distro="ubuntu-devel"
    - env: version="devel" distro="ubuntu-devel"
    - env: version="devel" distro="ubuntu-latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "x3U40DaujNvImNhDSUZg01+2AUF0L9OcZkcHTlwSz7MbYoALW1Uo+TIDJw578sgkgp2n0WViI5x7ai8wIr1vGy00d7vg/ZV1sOsU/kHYFJzx2bRJkFKA5o3cf3bWAhwrxgQEex0CUkJXnZKyVHOb4nbZNsMn0Nc+NMqrTtcnHpJDLbK7CQcFMT4CuS4d7/lvbiFkFuME2/gCQfBwitQcaZzwCG0o7H7Ilj2LU2PLXG4wplaNR8PyWT43poQ5colbUh5H94emY4M6YmbKyUb/tMZy9ALamNHFSYdUzSeWgYVTi/ppSar3Okb+Vdzfp6f2Iv5sl3p4pzUyuRbBSgQqt/7eV3qAxjGN1wqJBVmk8FiD75x9SxV+eeI/IKYHq4imc8l5Nmz/GmCQb9Ak30sz4yTyGRvALXuBVycTSFKj2zRihvmDv55l9uCCFOqVq3aUoA5riZaN6h2UWLX6Zrl4OFXWQdxRQWs/YUOWYyn+6mOEx1xtzYaSvP6+LoIEJGsHjmA9tHGJDl9xIU5tQLO9050pTg04uttuSvyZbD1ZjoWJBcDaZBBFTsvO2UAA6EzrQ8Raycmk41mBx7zISnprk5O4mqp8qFFeeCluDDzUv5ra4LqeIWyYsBDprBaeNRd5oes9sdGIlYCI6Oz3KCNLKi1hsPgpDOY+7nbwTo4YC2c="
  email: false
