---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux"
    - image="alpine"
    - image="alpine" tag="edge"
    - image="debian" tag="unstable"
    - image="debian"
    - image="centos"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="opensuse"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="alpine" tag="edge"
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "x3U40DaujNvImNhDSUZg01+2AUF0L9OcZkcHTlwSz7MbYoALW1Uo+TIDJw578sgkgp2n0WViI5x7ai8wIr1vGy00d7vg/ZV1sOsU/kHYFJzx2bRJkFKA5o3cf3bWAhwrxgQEex0CUkJXnZKyVHOb4nbZNsMn0Nc+NMqrTtcnHpJDLbK7CQcFMT4CuS4d7/lvbiFkFuME2/gCQfBwitQcaZzwCG0o7H7Ilj2LU2PLXG4wplaNR8PyWT43poQ5colbUh5H94emY4M6YmbKyUb/tMZy9ALamNHFSYdUzSeWgYVTi/ppSar3Okb+Vdzfp6f2Iv5sl3p4pzUyuRbBSgQqt/7eV3qAxjGN1wqJBVmk8FiD75x9SxV+eeI/IKYHq4imc8l5Nmz/GmCQb9Ak30sz4yTyGRvALXuBVycTSFKj2zRihvmDv55l9uCCFOqVq3aUoA5riZaN6h2UWLX6Zrl4OFXWQdxRQWs/YUOWYyn+6mOEx1xtzYaSvP6+LoIEJGsHjmA9tHGJDl9xIU5tQLO9050pTg04uttuSvyZbD1ZjoWJBcDaZBBFTsvO2UAA6EzrQ8Raycmk41mBx7zISnprk5O4mqp8qFFeeCluDDzUv5ra4LqeIWyYsBDprBaeNRd5oes9sdGIlYCI6Oz3KCNLKi1hsPgpDOY+7nbwTo4YC2c="
  email: false
