---
- robertdebock.bootstrap
- robertdebock.buildtools
- robertdebock.epel
- robertdebock.httpd
# If you have your database hosted on another instance, you don't need this
# role.
- robertdebock.mysql
- robertdebock.openssl
- robertdebock.php
- robertdebock.python_pip
- robertdebock.reboot
- robertdebock.selinux
