---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.epel
  - name: robertdebock.httpd
# If you have your database hosted on another instance, you don't need this
# role.
  - name: robertdebock.mysql
  - name: robertdebock.openssl
  - name: robertdebock.php
  - name: robertdebock.python_pip
  - name: robertdebock.reboot
  - name: robertdebock.selinux
