---

- name: assert | Test if roundcubemail_database_host is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_database_host is defined
      - roundcubemail_database_host is string
    quiet: yes

- name: assert | Test if roundcubemail_database_user is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_database_user is defined
      - roundcubemail_database_user is string
    quiet: yes

- name: assert | Test if roundcubemail_database_password is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_database_password is defined
      - roundcubemail_database_password is string
    quiet: yes

- name: assert | Test if roundcubemail_database_name is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_database_name is defined
      - roundcubemail_database_name is string
    quiet: yes

- name: assert | Test if roundcubemail_support_url is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_support_url is defined
      - roundcubemail_support_url is string
    quiet: yes

- name: assert | Test if roundcubemail_des_key is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_des_key is defined
      - roundcubemail_des_key is string
    quiet: yes

- name: assert | Test if roundcubemail_spellcheck_engine is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_spellcheck_engine is defined
      - roundcubemail_spellcheck_engine is string
      - roundcubemail_spellcheck_engine in [ "atd", "enchant", "google", "pspell" ]
    quiet: yes

- name: assert | Test if roundcubemail_default_host is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_default_host is defined
      - roundcubemail_default_host is string
    quiet: yes

- name: assert | Test if roundcubemail_default_port is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_default_port is defined
      - roundcubemail_default_port is number
    quiet: yes

- name: assert | Test if roundcubemail_smtp_server is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_smtp_server is defined
      - roundcubemail_smtp_server is string
    quiet: yes

- name: assert | Test if roundcubemail_smtp_port is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_smtp_port is defined
      - roundcubemail_smtp_port is number
    quiet: yes


- name: assert | Test if roundcubemail_smtp_user is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_smtp_user is defined
      - roundcubemail_smtp_user is string
    quiet: yes

- name: assert | Test if roundcubemail_smtp_pass is set correctly
  ansible.builtin.assert:
    that:
      - roundcubemail_smtp_pass is defined
      - roundcubemail_smtp_pass is string
    quiet: yes
