---
- name: test if roundcubemail_database_host is set correctly
  assert:
    that:
      - roundcubemail_database_host is defined
    quiet: yes

- name: test if roundcubemail_database_user is set correctly
  assert:
    that:
      - roundcubemail_database_user is defined
    quiet: yes

- name: test if roundcubemail_database_password is set correctly
  assert:
    that:
      - roundcubemail_database_password is defined
    quiet: yes

- name: test if roundcubemail_database_name is set correctly
  assert:
    that:
      - roundcubemail_database_name is defined
    quiet: yes

- name: test if roundcubemail_support_url is set correctly
  assert:
    that:
      - roundcubemail_support_url is defined
    quiet: yes

- name: test if roundcubemail_des_key is set correctly
  assert:
    that:
      - roundcubemail_des_key is defined
    quiet: yes

- name: test if roundcubemail_spellcheck_engine is set correctly
  assert:
    that:
      - roundcubemail_spellcheck_engine is defined
      - roundcubemail_spellcheck_engine in [ "atd", "enchant", "google", "pspell" ]
    quiet: yes
