---
# tasks file for roundcubemail
- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ roundcubemail_configuration[ansible_distribution]['package'] }}"

- name: install requirements
  package:
    name: "{{ item }}"
  with_items:
    - "{{ roundcubemail_configuration[ansible_distribution]['requirements'] }}"
  notify:
    - restart httpd

- name: configure php
  include_role:
    name: robertdebock.php
  vars:
    php_settings:
      upload_max_filesize:
        section: PHP
        value: 5M
      post_max_size:
        section: PHP
        value: 6M
      date.timezone:
        section: Date
        value: Europe/Amsterdam
      extension:
        section: PHP
        value: mcrypt.so
  notify:
    - restart httpd

- name: configure software
  template:
    src: config.inc.php.j2
    dest: "{{ roundcubemail_configuration[ansible_distribution]['file'] }}"
    owner: "{{ roundcubemail_configuration[ansible_distribution]['owner'] }}"
    group: "{{ roundcubemail_configuration[ansible_distribution]['group'] }}"
    mode: "{{ roundcubemail_configuration[ansible_distribution]['mode'] }}"

- name: configure httpd
  template:
    src: roundcubemail.conf.j2
    dest: "{{ roundcubemail_configuration[ansible_distribution]['httpd_conf'] }}"
  notify:
    - restart httpd
