---
# tasks file for roundcubemail
- name: install roundcubemail
  package:
    name: "{{ roundcubemail_packages }}"
    state: "{{ roundcubemail_package_state }}"

- name: install requirements
  package:
    name: "{{ roundcubemail_requirements }}"
    state: "{{ roundcubemail_package_state }}"
  notify:
    - restart httpd

- name: configure php
  include_role:
    name: robertdebock.php
  vars:
    php_settings:
      upload_max_filesize:
        section: PHP
        value: 5M
      post_max_size:
        section: PHP
        value: 6M
      date.timezone:
        section: Date
        value: Europe/Amsterdam
      extension:
        section: PHP
        value: mcrypt.so

- name: create roundcubemail_conf_dir
  file:
    path: "{{ roundcubemail_conf_dir }}"
    state: directory

- name: configure roundcubemail
  template:
    src: config.inc.php.j2
    dest: "{{ roundcubemail_conf_dir }}/{{ roundcubemail_file }}"
    owner: "{{ roundcubemail_owner }}"
    group: "{{ roundcubemail_group }}"
    mode: "{{ roundcubemail_mode }}"

- name: configure httpd
  template:
    src: roundcubemail.conf.j2
    dest: "{{ roundcubemail_httpd_configuration }}"
  notify:
    - restart httpd
