---
# tasks file for roundcubemail
- name: install requirements
  package:
    name: "{{ roundcubemail_requirements }}"
    state: present
  notify:
    - restart httpd
  register: roundcubemail_install_requirements
  until: roundcubemail_install_requirements is succeeded
  retries: 3

- name: install roundcubemail
  package:
    name: "{{ roundcubemail_packages }}"
    state: present
  register: roundcubemail_install_roundcubemail
  until: roundcubemail_install_roundcubemail is succeeded
  retries: 3
  notify:
    - import mysql table layout

- name: create roundcubemail_conf_dir
  file:
    path: "{{ roundcubemail_conf_dir }}"
    state: directory

- name: configure roundcubemail
  template:
    src: "{{ roundcubemail_file }}.j2"
    dest: "{{ roundcubemail_conf_dir }}/{{ roundcubemail_file }}"
    owner: "{{ roundcubemail_owner }}"
    group: "{{ roundcubemail_group }}"
    mode: "{{ roundcubemail_mode }}"

- name: configure selinux settings
  block:
    - name: place selinux type enforcement
      copy:
        src: my-roundcubemail.te
        dest: /etc/my-roundcubemail.te
      notify:
        - create roundcubemail selinux mod
        - create roundcubemail selinux pp
        - load roundcubemail selinux pp

    - name: enable selinux boolean httpd_setrlimit
      seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop:
        - httpd_setrlimit
        - daemons_enable_cluster_mode
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: configure httpd
  template:
    src: roundcube.conf.j2
    dest: "{{ roundcubemail_httpd_configuration }}"
  notify:
    - restart httpd
