---
# tasks file for roundcubemail
- name: install requirements
  package:
    name: "{{ roundcubemail_requirements }}"
    state: present
  notify:
    - restart httpd
  register: roundcubemail_install_requirements
  until: roundcubemail_install_requirements is succeeded
  retries: 3

- name: install roundcubemail
  package:
    name: "{{ roundcubemail_packages }}"
    state: present
  register: roundcubemail_install_roundcubemail
  until: roundcubemail_install_roundcubemail is succeeded
  retries: 3
  notify:
    - import mysql table layout

- name: create roundcubemail_conf_dir
  file:
    path: "{{ roundcubemail_conf_dir }}"
    state: directory

- name: configure roundcubemail
  template:
    src: config.inc.php.j2
    dest: "{{ roundcubemail_conf_dir }}/{{ roundcubemail_file }}"
    owner: "{{ roundcubemail_owner }}"
    group: "{{ roundcubemail_group }}"
    mode: "{{ roundcubemail_mode }}"

- name: place selinux type enforcement
  copy:
    src: my-roundcubemail.te
    dest: /etc/my-roundcubemail.te
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"
  notify:
    - create roundcubemail selinux mod
    - create roundcubemail selinux pp
    - load roundcubemail selinux pp

- name: configure httpd
  template:
    src: roundcubemail.conf.j2
    dest: "{{ roundcubemail_httpd_configuration }}"
  notify:
    - restart httpd
