---
# tasks file for roundcubemail
- name: install software
  package:
    name: "{{ roundcubemail_package }}"
    state: "{{ roundcubemail_package_state }}"

- name: install requirements
  package:
    name: "{{ roundcubemail_requirementes[ansible_distribution]
          | default(roundcubemail_requirementes['default']) }}"
    state: "{{ roundcubemail_package_state }}"
  notify:
    - restart httpd

- name: configure php
  include_role:
    name: robertdebock.php
  vars:
    php_settings:
      upload_max_filesize:
        section: PHP
        value: 5M
      post_max_size:
        section: PHP
        value: 6M
      date.timezone:
        section: Date
        value: Europe/Amsterdam
      extension:
        section: PHP
        value: mcrypt.so
  notify:
    - restart httpd

- name: configure software
  template:
    src: config.inc.php.j2
    dest: "{{ roundcubemail_file[ansible_distribution]
          | default(roundcubemail_file['default']) }}"
    owner: "{{ roundcubemail_owner }}"
    group: "{{ roundcubemail_group[ansible_distribution]
           | default(roundcubemail_group['default']) }}"
    mode: "{{ roundcubemail_mode[ansible_distribution]
           | default(roundcubemail_mode['default']) }}"

- name: configure httpd
  template:
    src: roundcubemail.conf.j2
    dest: "{{ roundcubemail_httpd_conf[ansible_distribution]
          | default(roundcubemail_httpd_configuration['default']) }}"
  notify:
    - restart httpd
