---
# tasks file for roundcubemail
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ roundcubemail_package }}"

- name: install requirements
  package:
    name: "{{ item }}"
  with_items:
    - "{{ roundcubemail_requirements }}"
  notify:
    - restart httpd

- name: configure php
  include_role:
    name: robertdebock.php
  vars:
    php_settings:
      upload_max_filesize:
        section: PHP
        value: 5M
      post_max_size:
        section: PHP
        value: 6M
      date.timezone:
        section: Date
        value: Europe/Amsterdam
      extension:
        section: PHP
        value: mcrypt.so
  notify:
    - restart httpd

- name: configure software
  template:
    src: config.inc.php.j2
    dest: "{{ roundcubemail_file }}"
    owner: "{{ roundcubemail_owner }}"
    group: "{{ roundcubemail_group }}"
    mode: "{{ roundcubemail_mode }}"

- name: configure httpd
  template:
    src: roundcubemail.conf.j2
    dest: "{{ roundcubemail_httpd_conf }}"
  notify:
    - restart httpd
