---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  vars:
    mysql_users:
      - name: roundcube
        password: pass
        priv: "roundcubemail.*:ALL"
    mysql_databases:
      - name: roundcubemail
    php_settings:
      upload_max_filesize:
        section: PHP
        value: 5M
      post_max_size:
        section: PHP
        value: 6M
      date.timezone:
        section: Date
        value: Europe/Amsterdam
      extension:
        section: PHP
        value: mcrypt.so

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.buildtools
    - robertdebock.python_pip
    - robertdebock.httpd
    - robertdebock.php
    - robertdebock.mysql
