---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    ../../vars/main.yml

  roles:
    - role: robertdebock.httpd
      httpd_vhosts:
        - name: docroot
          servername: roundcubemail.example.com
          documentroot: "{{ roundcubemail_install_directory }}"
    - role: ansible-role-roundcubemail
