---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    ../../vars/main.yml

  roles:
    - role: robertdebock.httpd
      httpd_vhosts:
        - name: docroot
          servername: localhost
          documentroot: "{{ roundcubemail_install_directory }}"
    - role: robertdebock.roundcubemail
