---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.php
    - role: robertdebock.buildtools
    - role: robertdebock.python-pip
    - role: robertdebock.httpd
    - role: ansible-role-roundcubemail
