---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Access the webinterface
      ansible.builtin.uri:
        url: "http://localhost/roundcubemail/"
        return_content: yes
      register: roundcubemail_access_the_webinterface
      failed_when:
        - "'Roundcube Webmail' not in roundcubemail_access_the_webinterface.content"
