---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: roundcubemail-ubuntu-latest
    image: ubuntu:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python2.7/site-packages/ara/plugins/callbacks
  inventory:
    group_vars:
      all:
        httpd_ignore_docker: no
scenario:
  name: ubuntu-latest
verifier:
  name: goss
  lint:
    name: yamllint
